run:
  timeout: 5m                 
  modules-download-mode: readonly

linters:
  enable:
    - gofmt            
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused

linters-settings:
  gofmt:
    simplify: true      
